name: flusstools
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip
  # scientific python
  - numpy
  - pandas
  # plotting
  - matplotlib
  - plotly
  # geospatial python
  - alphashape
  - earthpy
  - fiona
  - gdal
  - geopandas
  - geojson
  - laspy
  - pyshp
  - rasterio
  - rasterstats
  - scikit-image
  - shapely
  - tkinter
  # SQL DB mgmt
  - platform
  - sqlite3
 

