name: flusstools
channels:
  - conda-forge
  - defaults
  - blaze
  - anaconda

dependencies:
  - python=3.9
  - pip
  - tabulate
  # scientific python
  - numpy
  - pandas
  # plotting
  - matplotlib
  - plotly
  # geospatial python
  - alphashape
  - earthpy
  - fiona
  - gdal
  - geopandas
  - geojson
  - laspy
  - pyshp
  - rasterio
  - rasterstats
  - scikit-image
  - shapely
  - tk
  # SQL DB mgmt
  - sqlite3
